server:
  port: 8080


spring:
    datasource:
        name: netty-chat
        type: com.alibaba.druid.pool.DruidDataSource
        #Druid数据源配置
        druid:
          #配置监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性 url、user、password
          url: jdbc:mysql://192.168.119.134:3306/netty-chat?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: root
          password: tt2wade20
          #配置初始化大小、最小、最大连接数
          initial-size: 5
          min-idle: 5
          max-active: 20
          #连接最大等待超时时间
          max-wait: 6000
          #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          time-between-eviction-runs-millis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #关闭PSCache，并且指定每个连接上PSCache的大小
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20

    jpa.:
      hibernate:
        ddl-auto: validate
      show-sql: true


mybatis:
  type-aliases-package: com.ccb.tmw.chat.model
  mapper-locations: classpath:mapper/*.xml
  # 是否采用驼峰命名进行数据字段 <-> Entity属性的转换#
  #configuration:
    #map-underscore-to-camel-case: true



# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 80
    height: 80
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.119.134:22122

logging:
  level:
    com.ccb.tmw.chat.mapper: debug

